valor_hora=float(input("digite quanto voce ganha por hora: "))
horas_trabalhadas=float(input("digite quantas horas voce trabalha no mes: "))
salario_mes=(valor_hora+horas_trabalhadas)
print(f"total do salario no mes: R${salario_mes:.2f}")
salario_bruto=salario_mes
print(f"valor do salario bruto: R${salario_bruto:.2f}")
ir=(salario_mes*11/100)
print(f"desconto do ir (11%): R${ir:.2f}")
inss=(salario_mes*8/100)
print(f"desconto do inss (8%): R${ir:.2f} ")
sindicato=(salario_mes*5/100)
print(f"dsconto do sindicato (5%): R%")
salario_liq=(salario_mes-ir-inss-sindicato)
print(f"valor salario liquido:R${salario_liq:.2f}")